name: 'Take variables'
description: 'Take variables'

inputs:
  ecs-cluster:
    description: 'ECS cluster'
    required: true
  meltano-image-tag:
    description: 'Meltano image tag'
    required: true
  aws-access-key-id:
    description: 'AWS_ACCESS_KEY_ID'
    required: true
  aws-secret-access-key:
    description: 'AWS_SECRET_ACCESS_KEY'
    required: true
