name: Test

on:
  workflow_dispatch:
    inputs:
      release_number:
        description: 'Release number (image tag) (i.e., v.6.0)'
        required: true
        type: string

      environment:
        description: 'Environment'
        required: true
        type: choice
        default: dev
        options:
          - dev
          - qa
          - staging

jobs:
  deploy:
    name: Deploy image to Docker Hub
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get config
        id: configs
        uses: rchubi/git-coure/.github/actions/config@master

  deploy_qa:
    name: Deploy qa Deploy test
    needs: deploy
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Get config
        id: configs
        uses: rchubi/git-coure/.github/actions/config@master

      - name: Print result
        id: print_result
        env:
          var_all: ${{ steps.configs.outputs[format('ecs-cluster-{0}', inputs.environment)] }}
          var_dev: ${{ steps.configs.outputs.ecs-cluster-dev }}
        run: |
          echo ${{ inputs.var_all }}
          echo ${{ inputs.var_dev }}
