name: Deployment to Environments

on:
  workflow_dispatch:
    inputs:
      release_number:
        description: 'Release number (image tag) (i.e., v.6.0)'
        required: true
        type: string

      environment:
        description: 'Environment'
        required: true
        type: environment
        default: dev

jobs:
  deploy:
    name: Deploy image to Docker Hub
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Notify about start deploy ${{ inputs.environment }}
        id: notify_start
        uses: slack/webhook@v3.4.0
        env:
          SLACK_CHANNEL: Roman Chubinskyi
          SLACK_MESSAGE: 'Start release ' ${{ inputs.release_number }} 'to' ${{ inputs.environment }}
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        id: build-image
        run: docker build . --file Dockerfile -t bogggard/hello-world:$(date +%s)-${{ inputs.environment }} -t bogggard/hello-world:latest -t bogggard/hello-world:${{ inputs.environment }}

      - name: Push to Docker Hub
        id: push-image
        run: docker push bogggard/hello-world:${{ inputs.environment }}