name: Dev Deployment

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        id: build-image
        run: docker build . --file Dockerfile docker build . --file Dockerfile -t bogggard/hello-world:$(date +%s)-dev -t bogggard/hello-world:latest -t bogggard/hello-world:dev

      - name: Push to Docker Hub
        id: push-image
        run: docker push bogggard/hello-world:dev