name: End print

on:
  workflow_call:
    inputs:
      var_tag:
        description: 'Release number (image tag) (i.e., v.6.0)'
        required: true
        type: string

      var_env:
        description: 'Environment'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      var_tag:
        description: 'Release number (image tag) (i.e., v.6.0)'
        required: true
        type: string

      var_env:
        description: 'Environment'
        required: true
        type: choice
        default: dev
        options:
          - dev
          - qa
          - staging
          - USERNAME

jobs:
  print:
    name: End print
    runs-on: ubuntu-latest
    environment: ${{ inputs.var_env }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Print result
        id: print_result
        env:
          var_all: ${{ steps.configs.outputs[format('ecs-cluster-{0}', inputs.var_env)] }}
          var_dev: ${{ steps.configs.outputs.ecs-cluster-dev }}
        run: |
          echo ${{ inputs.var_all }}
          echo ${{ inputs.var_dev }}